### ISSUE TITLE
Can't add an output text

### ISSUE THREAD

**Issue by tilukpo** [univrsal/tuna#69] opened 2020-10-02 18:31 UTC
Im kinda new so.. maybe it's something simple..
https://youtu.be/vxQwo7n-Pcs
I've tried reinstalling (manually and with the control panel) but it seems that my previous configuration was saved..

**Comment by univrsal** [comment] 2020-10-02 18:32
Duplicate of #60

**Closed by univrsal** 2020-10-02 18:32 UTC
