### ISSUE TITLE
Music control dock does not work with Spotify Premium

### ISSUE THREAD

**Issue by dckface** [univrsal/tuna#82] opened 2020-11-06 19:05 UTC
**Describe the bug**
Buttons in music control dock (play, pause, previous, next) does not work at all, when Spotify Premium is used as source.

**To Reproduce**
1. Set-up Tuna to use Spotify as source. 
2. Start Spotify.
3. Start Tuna.
4. Add music control dock to OBS.
5. Clicking on Pause, Play or Next/Previous Track buttons does nothing, no matter how many times the buttons are clicked.

**Expected behavior**
I'd expect the buttons to normally control Spotify playback, when user has Spotify Premium.
I saw the other issues stating that it somehow works if you either register your own Spotify app in the dev portal to get your own client ID and secret, or if you click enough times. However this didn't help either.

**Comment by univrsal** [comment] 2020-11-06 20:22
can you send the obs studio log?

**Comment by dckface** [comment] 2020-11-07 14:41
Sure. I want to test it more first to rule out the possibility of incorrect use from my side though, so I'll send it later today.

**Comment by orion78fr** [comment] 2020-11-15 16:44
I have the same bug.
Here is the relevant logs :

```
17:35:35.608: [tuna] Refreshing Spotify token
17:35:35.902: [tuna] Spotify response: {
17:35:35.902:     "access_token": "REDACTED",
17:35:35.902:     "expires_in": 3600,
17:35:35.902:     "refresh_token": null,
17:35:35.902:     "scope": "user-modify-playback-state user-read-playback-state user-read-currently-playing",
17:35:35.902:     "token_type": "Bearer"
17:35:35.902: }
17:35:35.902: 
17:35:35.902: [tuna] Successfully logged in
17:35:35.902: [tuna] Successfully renewed Spotify token
17:40:04.777: [tuna] Couldn't run spotify command! HTTP code: 403
17:40:04.777: [tuna] Spotify controls only work for premium users!
17:40:04.777: [tuna] Response: 
17:40:07.105: [tuna] Couldn't run spotify command! HTTP code: 403
17:40:07.105: [tuna] Spotify controls only work for premium users!
17:40:07.105: [tuna] Response: 
```

**Comment by univrsal** [comment] 2020-11-15 21:26
@orion78fr can you please try [this](https://github.com/univrsal/tuna/actions/runs/364671395) version and try to use the play/pause option in the dock? It's most likely not gonna work, but I fixed the logging so now it should contain the response from spotify which should give a clearer description of the error.

**Comment by orion78fr** [comment] 2020-11-15 22:18
```
23:17:24.844: [tuna] Couldn't run spotify command! HTTP code: 403
23:17:24.844: [tuna] Spotify controls only work for premium users!
23:17:24.844: [tuna] Response: {
23:17:24.844:     "error": {
23:17:24.844:         "message": "Player command failed: Restriction violated",
23:17:24.844:         "reason": "UNKNOWN",
23:17:24.844:         "status": 403
23:17:24.844:     }
23:17:24.844: }
```

**Comment by orion78fr** [comment] 2020-11-15 22:18
Btw, if no music is playing, we have this error :

```
23:17:10.478: [tuna] Couldn't run spotify command! HTTP code: 404
23:17:10.478: [tuna] Spotify controls only work for premium users!
23:17:10.478: [tuna] Response: {
23:17:10.478:     "error": {
23:17:10.478:         "message": "Player command failed: No active device found",
23:17:10.478:         "reason": "NO_ACTIVE_DEVICE",
23:17:10.478:         "status": 404
23:17:10.478:     }
23:17:10.478: }
```

**Comment by univrsal** [comment] 2020-11-16 20:08
Welp seems like this'll probably never work: spotify/web-api#1205 I don't really know, seems like the API for this is just borked.

**Comment by orion78fr** [comment] 2020-11-17 02:05
Okay so strange thing, I have tried to curl directly from my terminal with the token I got in the response log of tuna parameters (here replaced with REDACTED), and it does work correctly :

```
OriOn78fr@Orion-pc-win8:~$ curl -H "Content-Type: application/json" -H "Content-Length: 0" -H "Authorization: Bearer REDACTED" -X PUT https://api.spotify.com/v1/me/player/play 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
OriOn78fr@Orion-pc-win8:~$ curl -H "Content-Type: application/json" -H "Content-Length: 0" -H "Authorization: Bearer REDACTED" -X PUT https://api.spotify.com/v1/me/player/pause
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```

I'm going to investigate further, maybe doing some changes in a fork and coming back to you.

**Comment by dckface** [comment] 2020-11-17 02:20
Hello, sorry it took me so long! I got busier than I expected. I tried it with the nightly version as well (the one you linked above) and I got following output in log file:
```
03:15:27.604: [tuna] Couldn't run spotify command! HTTP code: 429
03:15:27.604: [tuna] Spotify controls only work for premium users!
03:15:27.604: [tuna] Response: {
03:15:27.604:     "error": {
03:15:27.604:         "message": "API rate limit exceeded",
03:15:27.604:         "status": 429
03:15:27.604:     }
03:15:27.604: }
03:15:27.604: 
03:15:30.874: [tuna] Couldn't run spotify command! HTTP code: 403
03:15:30.874: [tuna] Spotify controls only work for premium users!
03:15:30.874: [tuna] Response: {
03:15:30.874:     "error": {
03:15:30.874:         "message": "Player command failed: Restriction violated",
03:15:30.874:         "reason": "UNKNOWN",
03:15:30.874:         "status": 403
03:15:30.874:     }
03:15:30.874: }
```
At first I was getting a bunch of rate limit failures(which I expected), but then I got the same error as @orion78fr (i.e. 403 without any specified reason). It's weird that I'm quite sure that it worked few weeks before I submitted this issue.

**Comment by orion78fr** [comment] 2020-11-17 03:15
If you are Rate Limiting, you are probably refreshing the song info too fast.
I'm actually trying to narrow down the issue, as it works by using curl in the console with the token from tuna, so I should work. I'm doing some changes in a fork and will tell you if I have something that works.

**Comment by orion78fr** [comment] 2020-11-17 04:21
@dckface Can you try [this build](https://github.com/orion78fr/tuna/suites/1513023239/artifacts/26594707) ? This should fix media controls.

**Comment by dckface** [comment] 2020-11-17 14:44
@orion78fr I just tried it and in this build Tuna doesn't work at all. The token wasn't filled in Tuna Settings, so I generated new authentication code (through the _Open login page_ button), but after trying to request new token, I got following ouptut in Tuna log.
```
= 2020.11.17 15:40 =
{
    "error": "invalid_client"
}
```
And OBS log had following output.
```
15:40:00.028: [tuna] Couldn't parse json response!
15:40:39.364: [tuna] Spotify response: {
15:40:39.364:     "access_token": null,
15:40:39.364:     "error": "invalid_client",
15:40:39.364:     "refresh_token": null
15:40:39.364: }
```

**Comment by orion78fr** [comment] 2020-11-17 15:10
That's strange because I don't think I modified any token renewing logic.

When I do this (Open login -> Paste the given code in the authentication code box -> Request token) I get a normal login :

```
16:03:29.574: [tuna] Spotify response: {
16:03:29.574:     "access_token": "REDACTED",
16:03:29.574:     "expires_in": 3600,
16:03:29.574:     "refresh_token": "REDACTED",
16:03:29.574:     "scope": "user-modify-playback-state user-read-playback-state user-read-currently-playing",
16:03:29.574:     "token_type": "Bearer"
16:03:29.574: }
```

**Comment by orion78fr** [comment] 2020-11-17 15:30
It seems I can't reproduce the invalid client issue.
Can you try [this build](https://github.com/univrsal/tuna/suites/1516138661/artifacts/26683004) ? I reverted something and it still works for me.

**Comment by dckface** [comment] 2020-11-17 16:03
I tried it, but I'm still getting the same error.

**Comment by dckface** [comment] 2020-11-17 16:06
And when I tried the nightly build from @univrsal, it was working again.

**Comment by univrsal** [comment] 2021-06-10 12:47
I'll just close this as it seems that the official API just doesn't support it

**Closed by univrsal** 2021-06-10 12:47 UTC
Labels: bug
