### ISSUE TITLE
Tuna don't work

### ISSUE THREAD

**Issue by Penicilline28** [univrsal/tuna#66] opened 2020-09-30 12:23 UTC
Repro:

- Open Tuna Settings
- Select Basics tab
- Click "Add new"
- the explorer button for song info path is unresponsive

Like #64 

This issue was found using Tuna v1.5.0 in OBS Studio 26.0.0

**Comment by univrsal** [comment] 2020-09-30 16:45
duplicate of #60

**Closed by univrsal** 2020-09-30 16:45 UTC
