### ISSUE TITLE
Empty Song info outputs, can't add any

### ISSUE THREAD

**Issue by xYorYx** [univrsal/tuna#68] opened 2020-10-01 04:40 UTC
Hello! I have installed tuna few hours ago and been struggling with it since then. I have connected it to Spotify without a problem, the Logged in green text is shown and it downloads the song art of the current playing song. My issue is that the Song info outputs is absolutely empty and I can't figure how to add any, so I can't show what song is playing on the stream.

**Comment by univrsal** [comment] 2020-10-01 16:46
Duplicate of #60

**Closed by univrsal** 2020-10-01 16:46 UTC
