### ISSUE TITLE
Support obs vlc source

### ISSUE THREAD

**Issue by amosbird** [univrsal/tuna#5] opened 2019-12-26 14:14 UTC
Hello, nice plugin! I wonder if it's possible to support vlc source in obs-studio. That is, I don't play music on my host, only streaming them. It's a desperate feature to have now-playing information being streamed too.

**Comment by univrsal** [comment] 2019-12-26 17:30
I'm actually looking into that right now. I've told someone before that I didn't want to add it because it should rather be added to the vlc source itself.
If my attempt works it'll have to rely on a dirty hack that could break in between obs versions, which means if I add it, VLC source support will disable itself if the obs version changed.

**Comment by amosbird** [comment] 2019-12-26 17:33
> should rather be added to the vlc source itself.

That's interesting. I don't see any visual frames added after I attach a audio VLC source (it definitely comes with some audio track covers). So how can changing VLC source only help?

**Comment by univrsal** [comment] 2019-12-26 17:46
I mean that it would make more sense for the vlc source to have an option to output the song information to a text file, because the vlc source has direct access to that information, while I have to jump through some hoops to make it work

**Comment by amosbird** [comment] 2019-12-26 17:58
ah, the ` vlc source` , I misread it as the vlc code base lol.  Yeah, that makes sense to me.

>  VLC source support will disable itself if the obs version changed.

hmm, why does it have so tight intergration to obs? Anyway I still think it's a good direction even if only current version is supported. For advanced users they can figure out why it breaks (should be trivially fixable imo) and just do some local patch to get on.

**Comment by univrsal** [comment] 2019-12-26 18:04
For this to work I have to take the source from obs and then access data within it that isn't exposed publicly, which means I have to cast it, this assumes that the data structure has not changed since I compiled the plugin, but if obs updates there's a chance that it has, which would result in the plugin interpreting the memory wrong and a subsequent crash. I could just assume that the structure never changes, but I kinda want to play it safe.

**Comment by amosbird** [comment] 2019-12-26 18:21
If "play it safe" means not to crash obs, we can just do some version checks and bail. It's up to the user who want this feature to adapt the structure changes. Also I think `vlc source` upstream might consider exporting those structures if this project goes popular.

**Comment by univrsal** [comment] 2019-12-26 18:26
> If "play it safe" means not to crash obs, we can just do some version checks and bail.
that's exactly what I said I was going to do. The user can't just adapt the structure changes, it requires the plugin to be updated and recompiled

**Comment by amosbird** [comment] 2019-12-26 18:31
I mean a user could `updated and recompiled` by himself if the feature is early needed...

> that's exactly what I said I was going to do. 

ok.. so do you still have plan to implement this? 

> They very likely will not change it just so one plugin can access a bit of private data

and 

> I mean that it would make more sense for the vlc source to have an option to output the song information to a text file

perhaps we can submit a pr to obs with that option and builds the plugin against that patched obs? To some extent it might get merged..

**Comment by univrsal** [comment] 2019-12-26 18:53
If someone wants to recompile the plugin to make it work after an update they can do that, but I don't want the average user to have to deal with a crash.
> ok.. so do you still have plan to implement this?

I'll see how my testing goes.
> perhaps we can submit a pr to obs with that option and builds the plugin against that patched obs? To some extent it might get merged..

Maybe, but I'll work on the plugin for now

**Comment by amosbird** [comment] 2019-12-26 18:56
> but I'll work on the plugin for now

Awesome! can't wait to hear some good news :)

**Comment by univrsal** [comment] 2019-12-26 21:37
![image](https://user-images.githubusercontent.com/8353672/71491282-1f7c4300-2830-11ea-86d8-461a18568869.png)
Welp, that's how far I've gotten for now. I'll still need to do some more testing to makre sure it doesn't crash, but it seems to work.

**Comment by amosbird** [comment] 2019-12-27 00:36
Impressive :)  I'll help test

**Comment by amosbird** [comment] 2019-12-27 00:45
Hmm, I realized you're also on archlinux, however a simple build fails with 

```
~/git/tuna/release ~/git/tuna
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindLibcurl.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Libcurl", but
  CMake did not find one.

  Could not find a package configuration file provided by "Libcurl" with any
  of the following names:

    LibcurlConfig.cmake
    libcurl-config.cmake

  Add the installation prefix of "Libcurl" to CMAKE_PREFIX_PATH or set
  "Libcurl_DIR" to a directory containing one of the above files.  If
  "Libcurl" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/amos/git/tuna/release/CMakeFiles/CMakeOutput.log".
~/git/tuna
```

I cannot find any archlinux package providing libcurl cmake modules...

**Comment by univrsal** [comment] 2019-12-27 12:22
The plugin requires a working development environment of obs-studio, just follow [this](https://github.com/obsproject/obs-studio/wiki/install-instructions#linux-build-directions) and then [this](https://github.com/univrsal/input-overlay/wiki/Compiling) (but replace ``input-overlay`` with tuna and stop after ``add_subdirectory(input-overlay)``)

**Comment by amosbird** [comment] 2019-12-29 17:47
https://github.com/univrsal/tuna/blob/master/src/util/vlc_internal.h#L14

The include order has to be 

```
#include <libvlc_media.h>
#include <libvlc_media_list.h>

#include <libvlc_events.h>

#include <libvlc_media_player.h>

#include <libvlc_media_list_player.h>

```

**Comment by amosbird** [comment] 2019-12-29 18:32
btw, when restarting obs, tuna resets vlc source to `tuna.vlc.none`

![image](https://user-images.githubusercontent.com/5085485/71561066-9faedc80-2aac-11ea-9502-519d388e8708.png)

**Comment by univrsal** [comment] 2019-12-29 19:42
yeah that's not supposed to happen. Also I copied the include order directly from the obs vlc source, so it should be correct

**Comment by amosbird** [comment] 2019-12-29 19:43
> Also I copied the include order directly from the obs vlc source, so it should be correct

I noticed you've reformat it

**Comment by univrsal** [comment] 2019-12-29 19:44
I ran clang format if that's what you mean

**Comment by amosbird** [comment] 2019-12-29 19:45
yup, that reorders includes

**Comment by amosbird** [comment] 2019-12-29 19:47
btw,  > yeah that's not supposed to happen

how can I inspect this...

**Comment by univrsal** [comment] 2019-12-29 19:49
I think it's trying to select the source that was selected previously before the list box is filled with all vlc sources, I'm not sure though
https://github.com/univrsal/tuna/blob/master/src/query/vlc_obs_source.cpp#L173
https://github.com/univrsal/tuna/blob/master/src/gui/tuna_gui.cpp#L449

**Comment by amosbird** [comment] 2019-12-29 19:51
hmm, I'll try hard coding one.  Btw, I use tuna vlc only to dump the current playing music info to a file. And I use that file to build a text source. do I use it correctly?

**Comment by univrsal** [comment] 2019-12-29 19:57
yeah

**Comment by amosbird** [comment] 2019-12-29 19:59
I commented out this line https://github.com/univrsal/tuna/blob/master/src/gui/tuna_gui.cpp#L452  and now the source dialog shows the correct vlc source. But after restarting, it still shows `No song playing`. I have to open tuna setting and click the apply button to have it work.

**Comment by univrsal** [comment] 2019-12-29 19:59
I'll look into it

**Comment by univrsal** [comment] 2020-02-11 20:00
Well I've made a pre-release with the feature in it. Once I get some feedback I'll mark it as a proper release. I haven't gotten around to making a linux build, but I'll try doing that soon.

**Comment by lcatlas** [comment] 2020-02-14 17:29
All is really good, but can't get anything exept Song title from vlc with avi/mp4 etc. Is there anyway? Only getting something like full title name.mp3/mp4/avi etc.

Thanks alot!

**Comment by univrsal** [comment] 2020-02-14 19:29
I might add an option to remove file extensions, but ideally you'd use properly tagged music, which is usually the case when you get it from bandcamp etc.
If the files aren't tagged correctly VLC probably just resorts to using the file name and there's no way to get any more information than that.

**Comment by lcatlas** [comment] 2020-02-14 19:42
Got it, thanks alot, will try to fix it.

**Comment by lcatlas** [comment] 2020-02-15 02:23
Got an OBS crush (VLC fault) after 10 mins, wasn't getting them for 2-3 weeks atleast :)
Logs: https://obsproject.com/logs/sgh8bDb_Nuu82Wim

**Comment by univrsal** [comment] 2020-02-15 13:23
were you doing anything specific? I also need the log file (not the crash log)

**Comment by lcatlas** [comment] 2020-02-15 14:25
Nothing, just opened program and it was running. 1 browser was open. Cpu load 15%. No streaming (only ndi)
I can't post log at this time - OBS crushed, so it didn't saved log at this time.

**Comment by univrsal** [comment] 2020-02-17 14:11
Could you reproduce the crash? Because I've been leaving it running with a bunch of files and it hasn't crashed yet

**Comment by lcatlas** [comment] 2020-02-18 04:02
Hello, still running and all good, even on stream, so will report back if i`ll reproduce it. Thanks alot.

**Comment by treier57lol** [comment] 2020-02-22 15:09
Trying the new pre-release but can't find any sources in the VLC tab. Is there no Linux support yet? Running on Kubuntu 19.04, OBS 24.0.3, VLC 3.0.8.

**Comment by univrsal** [comment] 2020-02-22 17:26
No, all platforms are supported. Do you have a vlc source added in obs? I also need your obs log.

**Comment by treier57lol** [comment] 2020-02-22 17:58
Sorry, problem was I forgot to add a VLC Source.

**Comment by lcatlas** [comment] 2020-02-25 14:37
Hello, Univrsal, i think another tag related crash (think) obs support said media source.
Both logs (crash and normal one) - not sure, converted to mp4 file. WIll try again avi today.
[2020-02-23 19-50-49.txt](https://github.com/univrsal/tuna/files/4250469/2020-02-23.19-50-49.txt)
Crash about avcodec-58.dll - ffmpeg. (in crash log, can add if needed)

Not sure 100% that's it's tuna related, but never seen this crash before. Just in case.

**Comment by univrsal** [comment] 2020-02-25 15:34
Yeah I need the crashlog

**Comment by lcatlas** [comment] 2020-02-26 08:07
[Crash 2020-02-24 00-15-56.txt](https://github.com/univrsal/tuna/files/4254190/Crash.2020-02-24.00-15-56.txt)
Hello!
Converted back to avi and added tags with another program - no problems at last stream (5+ hours)

Will test more ofc.

**Comment by univrsal** [comment] 2020-02-26 13:27
Yeah this doesn't seem to be an issue with tuna but rather something in obs, I'd recommend you report it to the devs and see if they have any idea what the issue is.

**Comment by univrsal** [comment] 2020-03-08 20:45
I made a new proper release with VLC support so I'll just close this issue now. If you find any new bugs just open a new issue.

**Closed by univrsal** 2020-03-08 20:45 UTC

**Comment by tatunts** [comment] 2020-12-18 12:27
> I might add an option to remove file extensions, but ideally you'd use properly tagged music, which is usually the case when you get it from bandcamp etc.
> If the files aren't tagged correctly VLC probably just resorts to using the file name and there's no way to get any more information than that.

Hello Sir! Thanks for this great software :) I was wondering if there's a way to use VLC and remove the extension part from the tittle, since I don't have any metadata on my mp3 files? Thanks!

![image](https://user-images.githubusercontent.com/25224882/102614612-4a336b80-4113-11eb-89ae-a1410041fb19.png)

**Comment by univrsal** [comment] 2020-12-18 20:36
If it's just one file I'd recommend you tag the file properly. I've added an option to remove extensions, but it'll take a bit until it'll be released.
