### ISSUE TITLE
Google Play Music Desktop Player not Recognized by Tuna

### ISSUE THREAD

**Issue by kyrthrix** [univrsal/tuna#77] opened 2020-10-14 21:12 UTC
As the title says; I've done everything said in the instructions- I made the text files, linked them all up, created the artist - album, song, etc. parts in the tuna settings, and have it selected to GPMDP... and regardless of whether the program is on Google Play Music or Youtube Music, it never changes the lack of recognization from tuna. I've been pulling at my hair just trying to find something that works with youtube music to no avail, and this seemed like my best bet. Help? 😢

**Comment by univrsal** [comment] 2020-10-15 16:27
duplicate of #59 
Are you using the player to play music from youtube music, because I think that the API that they offer just doesn't work right now. I don't own any music on google music so I can only test it with YouTube music and if I check the file that should contain the information there's nothing in there

**Closed by univrsal** 2020-10-15 16:27 UTC

**Comment by univrsal** [comment] 2020-10-15 16:40
Also can you open this file %APPDATA%\Google Play Music Desktop Player\json_store\playback.json while music is playing and see what text it contains? Because that's where the information should be saved if it's working

**Comment by kyrthrix** [comment] 2020-10-15 22:30
> Also can you open this file %APPDATA%\Google Play Music Desktop Player\json_store\playback.json while music is playing and see what text it contains? Because that's where the information should be saved if it's working

I am using the player to try playing music from both Google Play and Youtube Music, and when I went to that location in the %appdata% it writes that "playing": true, but most of the other settings are "null" for some reason.

![](https://cdn.discordapp.com/attachments/487759925213265920/766427796683620352/unknown.png)

**Comment by kyrthrix** [comment] 2020-10-15 22:33
Ah, it appears to work when I switch it to Google Play, yet when I switched it to GP while I had everything set up for OBS it still did not read the song/album/artist?
![image](https://user-images.githubusercontent.com/72892238/96192886-f8087b00-0f14-11eb-91c7-08093d5ec5bf.png)

**Comment by univrsal** [comment] 2020-10-16 16:54
welp looks like it's not reading the file then, I'll look into it. I'll post in #59 when I find anything new

**Comment by kyrthrix** [comment] 2020-10-16 21:32
I appreciate it!
